apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "common.names.fullname" . }}-defrag-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "common.labels.standard" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.names.fullname" . }}-defrag-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "common.labels.standard" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  #name: {{ include "common.names.fullname" . }}-defrag-sa
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "common.names.fullname" . }}-defrag-role
  apiGroup: rbac.authorization.k8s.io
